### ISSUE TITLE
No longer detecting AWS announcements 😞 

### ISSUE THREAD

**Issue by karl-cardenas-coding** [circa10a/go-aws-news#79]
## Description

It appears that AWS news has been broken since December. Upon closer inspection, it looks like the AWS site's HTML structure has changed. I suspect this is the primary reason behind the lack of reporting.

**Comment by circa10a** [comment]
Oh no, thanks for reporting! I'll dig into what changed and will fix accordingly 👍

**Comment by circa10a** [comment]
Looks like AWS has an API now powering their site. Just need to rewrite to use this instead of parsing the HTML. I can probably have it done by end of weekend if time permits.

- filters: https://aws.amazon.com/api/dirs/items/search?item.directoryId=whats-new&sort_by=item.additionalFields.postDateTime&sort_order=desc&size=20&item.locale=en_US&q=test&q_operator=AND&tags.id=whats-new%23year%232020
- raw items: https://aws.amazon.com/api/dirs/items/search?item.directoryId=whats-new&size=1000

**Comment by karl-cardenas-coding** [comment]
That's a better solution. So long HTML parsing 🙂

**Comment by circa10a** [comment]
@karl-cardenas-coding `v1.8.0` was just put released and seems to fix everything

**Comment by karl-cardenas-coding** [comment]
You da man @circa10a , much appreciated good sir!

**Comment by karl-cardenas-coding** [comment]
Update: Upgraded to the newest version. It's working like a charm @circa10a 🥳

**Comment by circa10a** [comment]
Sweet! Thanks @karl-cardenas-coding !

**Comment by amentee** [comment]
@circa10a Where is the information documented that AWS site is now powered by api call whose baseURL is - https://aws.amazon.com/api/dirs/items/search . How did you figure that out?

**Comment by circa10a** [comment]
@amentee I loaded the what's new site and used chrome dev tools to see what sources were being called:

![Screenshot 2024-11-21 at 6 44 02 AM](https://github.com/user-attachments/assets/b5d294a2-ba51-4bf5-b2ad-7b0a0dab1abf)
